[package]
name = "nock"
version = "0.4.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
keywords = ["vm"]
description = "A stateless virtual machine"
repository = "https://github.com/rsaarelm/nock-rs"
license = "MIT OR Apache-2.0"

[dependencies]
num = "0.1"
fnv = "1.0"
